<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Создание-датафрейма" data-toc-modified-id="Создание-датафрейма-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Создание датафрейма</a></span></li><li><span><a href="#Преобразования-столбцов" data-toc-modified-id="Преобразования-столбцов-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Преобразования столбцов</a></span><ul class="toc-item"><li><span><a href="#id" data-toc-modified-id="id-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>id</a></span></li><li><span><a href="#tags" data-toc-modified-id="tags-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>tags</a></span></li><li><span><a href="#light" data-toc-modified-id="light-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>light</a></span></li><li><span><a href="#point" data-toc-modified-id="point-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>point</a></span></li><li><span><a href="#nearby" data-toc-modified-id="nearby-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>nearby</a></span></li><li><span><a href="#region" data-toc-modified-id="region-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>region</a></span></li><li><span><a href="#scheme" data-toc-modified-id="scheme-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>scheme</a></span></li><li><span><a href="#address" data-toc-modified-id="address-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>address</a></span></li><li><span><a href="#weather" data-toc-modified-id="weather-2.9"><span class="toc-item-num">2.9&nbsp;&nbsp;</span>weather</a></span></li><li><span><a href="#category" data-toc-modified-id="category-2.10"><span class="toc-item-num">2.10&nbsp;&nbsp;</span>category</a></span></li><li><span><a href="#datetime" data-toc-modified-id="datetime-2.11"><span class="toc-item-num">2.11&nbsp;&nbsp;</span>datetime</a></span></li><li><span><a href="#severity" data-toc-modified-id="severity-2.12"><span class="toc-item-num">2.12&nbsp;&nbsp;</span>severity</a></span></li><li><span><a href="#vehicles" data-toc-modified-id="vehicles-2.13"><span class="toc-item-num">2.13&nbsp;&nbsp;</span>vehicles</a></span></li><li><span><a href="#dead_count" data-toc-modified-id="dead_count-2.14"><span class="toc-item-num">2.14&nbsp;&nbsp;</span>dead_count</a></span></li><li><span><a href="#participants" data-toc-modified-id="participants-2.15"><span class="toc-item-num">2.15&nbsp;&nbsp;</span>participants</a></span></li><li><span><a href="#injured_count" data-toc-modified-id="injured_count-2.16"><span class="toc-item-num">2.16&nbsp;&nbsp;</span>injured_count</a></span></li><li><span><a href="#parent_region" data-toc-modified-id="parent_region-2.17"><span class="toc-item-num">2.17&nbsp;&nbsp;</span>parent_region</a></span></li><li><span><a href="#road_conditions" data-toc-modified-id="road_conditions-2.18"><span class="toc-item-num">2.18&nbsp;&nbsp;</span>road_conditions</a></span></li><li><span><a href="#participants_count" data-toc-modified-id="participants_count-2.19"><span class="toc-item-num">2.19&nbsp;&nbsp;</span>participants_count</a></span></li><li><span><a href="#participant_categories" data-toc-modified-id="participant_categories-2.20"><span class="toc-item-num">2.20&nbsp;&nbsp;</span>participant_categories</a></span></li></ul></li><li><span><a href="#Преобразование-1" data-toc-modified-id="Преобразование-1-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Преобразование 1</a></span></li><li><span><a href="#Преобразование-2" data-toc-modified-id="Преобразование-2-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Преобразование 2</a></span></li><li><span><a href="#Гипотезы" data-toc-modified-id="Гипотезы-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Гипотезы</a></span><ul class="toc-item"><li><span><a href="#Водители-со-стажем-4-6-лет-опаснее,-чем-новички-с-опытом-до-3-х-лет" data-toc-modified-id="Водители-со-стажем-4-6-лет-опаснее,-чем-новички-с-опытом-до-3-х-лет-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Водители со стажем 4-6 лет опаснее, чем новички с опытом до 3-х лет</a></span></li><li><span><a href="#В-темное-время-суток-отсутствие-освещение-делает-ДТП-опаснее." data-toc-modified-id="В-темное-время-суток-отсутствие-освещение-делает-ДТП-опаснее.-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>В темное время суток отсутствие освещение делает ДТП опаснее.</a></span></li><li><span><a href="#Большой-транпорт-опаснее-(тип)" data-toc-modified-id="Большой-транпорт-опаснее-(тип)-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Большой транпорт опаснее (тип)</a></span></li></ul></li></ul></div>

[__Всю визиализацию мы будем делать в Yandex DataLen__](https://datalens.yandex.cloud/hsqg7wksso265-dashbord-dtp) 

# Вторая часть

## Создание датафрейма

Мы соединим 3 файла в один, проанализируем его, поймем как с ним работать, а далее перейдем к работе над всеми 85 файлами.

In [1]:
import requests
from tqdm import tqdm
import os
import pandas as pd
import geopandas as gpd
import json 
import ast
from tqdm import tqdm

import warnings
warnings.filterwarnings('ignore')


In [2]:
# записываем путь к файлам
path = '/Users/juliagrebeneva/Desktop/test/'  

# Получить список всех файлов в директории
file_names = [f for f in os.listdir(path) if f.endswith('.geojson')]

# Загрузка и склеивание всех файлов
gdfs = [gpd.read_file(os.path.join(path, file_name)) for file_name in file_names]
data = gpd.GeoDataFrame(pd.concat(gdfs, ignore_index=True), crs=gdfs[0].crs)



In [3]:
# смотрим, как выглядит файл
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
data.head(5)

id                                               tags  \
0  2869171                [Дорожно-транспортные происшествия]   
1  2320091  [Дорожно-транспортные происшествия, ДТП и пост...   
2  2321011  [Дорожно-транспортные происшествия, ДТП и пост...   
3  2576909                [Дорожно-транспортные происшествия]   
4  2575209                [Дорожно-транспортные происшествия]   

                 light                                  point  \
0  Светлое время суток      {'lat': 53.3912, 'long': 83.7879}   
1  Светлое время суток  {'lat': 53.345833, 'long': 83.666389}   
2  Светлое время суток    {'lat': 53.19706, 'long': 83.39688}   
3  Светлое время суток      {'lat': 53.3764, 'long': 83.7142}   
4  Светлое время суток  {'lat': 53.343071, 'long': 83.794366}   

                                              nearby   region scheme  \
0              [Жилые дома индивидуальной застройки]  Барнаул    830   
1  [Многоквартирные жилые дома, Внутридворовая те...  Барнаул    880   
2  [Административные здания, Остановка общественн...  Барнаул    960   
3  [Выезд с прилегающей территории, Административ...  Барнаул    130   
4  [Многоквартирные жилые дома, Жилые дома индиви...  Барнаул    500   

                            address     weather           category  \
0                              None      [Ясно]  Наезд на пешехода   
1       г Барнаул, ул Сиреневая, 11  [Пасмурно]       Иной вид ДТП   
2         г Барнаул, ул Попова, 165      [Ясно]  Падение пассажира   
3  г Барнаул, ул Петра Сухова, 83 А      [Ясно]       Столкновение   
4    г Барнаул, ул Партизанская, 26      [Ясно]       Столкновение   

             datetime severity  \
0 2023-05-24 19:30:00   Легкий   
1 2015-09-16 13:00:00   Легкий   
2 2017-08-25 15:30:00   Легкий   
3 2021-05-29 19:40:00  Тяжёлый   
4 2021-05-25 16:40:00   Легкий   

                                            vehicles  dead_count  \
0  [ { "year": 2015, "brand": "Прочие марки ТС", ...           0   
1  [ { "year": 2002, "brand": "TOYOTA", "color": ...           0   
2  [ { "year": 1981, "brand": "DAIMLER", "color":...           0   
3  [ { "year": 2001, "brand": "HONDA", "color": "...           0   
4  [ { "year": 2014, "brand": "NISSAN", "color": ...           0   

                                        participants  injured_count  \
0  [ { "role": "Пешеход", "gender": "Мужской", "v...              1   
1                                                [ ]              1   
2                                                [ ]              1   
3                                                [ ]              1   
4                                                [ ]              1   

    parent_region                                    road_conditions  \
0  Алтайский край                                            [Сухое]   
1  Алтайский край                                            [Сухое]   
2  Алтайский край                                            [Сухое]   
3  Алтайский край  [Сухое, Отсутствие, плохая различимость горизо...   
4  Алтайский край  [Сухое, Отсутствие, плохая различимость горизо...   

   participants_count                   participant_categories  \
0                   2  [Все участники, Пешеходы, Мотоциклисты]   
1                   2                    [Дети, Все участники]   
2                   3                    [Дети, Все участники]   
3                   3            [Мотоциклисты, Все участники]   
4                   2                          [Все участники]   

                    geometry  
0  POINT (83.78790 53.39120)  
1  POINT (83.66639 53.34583)  
2  POINT (83.39688 53.19706)  
3  POINT (83.71420 53.37640)  
4  POINT (83.79437 53.34307)

In [4]:
for column in data.columns:
    print(f"{column}: {data[column].iloc[107]}")

id: 2310319
tags: ['Дорожно-транспортные происшествия']
light: Светлое время суток
point: {'lat': 53.3408, 'long': 83.6964}
nearby: ['Многоквартирные жилые дома', 'Административные здания', 'Нерегулируемый перекрёсток неравнозначных улиц (дорог)', 'Подход к мосту, эстакаде, путепроводу', 'Нерегулируемый пешеходный переход', 'Одиночный торговый объект, являющийся местом притяжения транспорта и (или) пешеходов']
region: Барнаул
scheme: 070
address: г Барнаул, ул Малахова, 123
weather: ['Ясно']
category: Столкновение
datetime: 2020-05-24 10:00:00
severity: Легкий
vehicles: [ { "year": 2013, "brand": "RENAULT", "color": "Белый", "model": "Duster", "category": "В-класс (малый) до 3,9 м", "participants": [ { "role": "Пассажир", "gender": "Женский", "violations": [ ], "health_status": "Раненый, находящийся (находившийся) на амбулаторном лечении, либо в условиях дневного стационара", "years_of_driving_experience": null }, { "role": "Водитель", "gender": "Мужской", "violations": [ ], "health_st

In [5]:
data.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 47820 entries, 0 to 47819
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype         
---  ------                  --------------  -----         
 0   id                      47820 non-null  int64         
 1   tags                    47820 non-null  object        
 2   light                   47820 non-null  object        
 3   point                   47820 non-null  object        
 4   nearby                  47820 non-null  object        
 5   region                  47820 non-null  object        
 6   scheme                  45911 non-null  object        
 7   address                 45586 non-null  object        
 8   weather                 47820 non-null  object        
 9   category                47820 non-null  object        
 10  datetime                47820 non-null  datetime64[ns]
 11  severity                47820 non-null  object        
 12  vehicles                47820 non-null

В файле у нас 21 столбцец. По структуре мы видим, что у нас есть колонки с числовыми значениями, строковыми, даты,  списки, словари, списки словарей. Мы разберем каждый столбец, решим какие столбцы нам понадобятся для решения задач, составим нужные нам датасеты и преобразуем их для дальнейшего анализа. Так же заметим, что изначально файл весит 7.7 MB, будем пробовать его уменьшать.

## Преобразования столбцов

### id

In [6]:
data['id'].duplicated().sum()

0

Столбец id содержит уникальный номер для каждого ДТП. Если посмотреть на значения, то они находятся в разряде миллионов, значит мы можем перевести тип с int64 на int32, чтобы этот столбец занимал меньше места. Он будет использоваться во всех датасетах, поэтому это может помочь в сокращении памяти.

In [7]:
#проверяем, входят ли значения id в интервал для int32
print(max(data['id']) <= 2147483647, min(data['id']) >= -2147483648 )


True True


In [8]:
data['id']=data['id'].astype('int32')

In [9]:
print('Объем файла',round(data.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 7.48 MB


Память уменьшилась до 7.48 MB.

### tags

Столбец tags содержит списки, сначала посчитаем максимальное количество элементов в списках, далее мы избавимся от них и посмотрим, что у нас получилось.

In [10]:
data['tags'].apply(len).max()

3

In [11]:
data['tags'].apply(lambda x: ','.join(x)).unique()

array(['Дорожно-транспортные происшествия',
       'Дорожно-транспортные происшествия,ДТП и пострадавшие дети в возрасте до 16 лет',
       'Дорожно-транспортные происшествия,ДТП и пострадавшие пешеходы, из-за наезда на пешеходов, на пешеходных переходах, по вине пешеходов',
       'Дорожно-транспортные происшествия,ДТП и пострадавшие пешеходы, из-за наезда на пешеходов, на пешеходных переходах, по вине пешеходов,ДТП и пострадавшие дети в возрасте до 16 лет',
       'Дорожно-транспортные происшествия,ДТП и пострадавшие дети в возрасте до 16 лет,ДТП и пострадавшие пешеходы, из-за наезда на пешеходов, на пешеходных переходах, по вине пешеходов'],
      dtype=object)

Всего у нас три вида ДТП: ДТП, ДТП с детьми и ДТП с пешеходами. Заменим эти длинные названия на цифры от 1 до 3 соответственно. Таким образом у нас будет числовой столбец.

In [12]:
def map_values(lst):
    values = []
    
    if 'Дорожно-транспортные происшествия' in lst:
        values.append('1')
    if 'ДТП и пострадавшие дети в возрасте до 16 лет' in lst:
        values.append('2')
    if 'ДТП и пострадавшие пешеходы, из-за наезда на пешеходов, на пешеходных переходах, по вине пешеходов' in lst:
        values.append('3')
    
    return ''.join(values) if values else '0'




In [13]:
data['tags'] = data['tags'].apply(map_values)

In [14]:
data['tags'] = data['tags'].astype('int16')

In [15]:
print(data['tags'].unique())

[  1  12  13 123]


In [16]:
print('Объем файла',round(data.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 7.21 MB


Размер файла уменьшился, столбец можно будет использовать, можно будет подумать как его преобразовать.

### light

In [17]:
data['light'].unique()

array(['Светлое время суток', 'В темное время суток, освещение включено',
       'Сумерки', 'В темное время суток, освещение не включено',
       'В темное время суток, освещение отсутствует', 'Не установлено'],
      dtype=object)

В столбце light всего 5 уникальных значений, в нем ничего менять не будем.

### point

Столбец point содержит кординаты ДТП. Для дальнейшей визуализации мы будем использовать Yandex DataLens, поэтому представим переделаем столбец из {'lat': 53.3912, 'long': 83.7879} в такой вид [53.3912,83.7879]. 

У нас есть второй столбец с геоданными в столбце geometry, но мы не будем его использовать. Поэтому в общий файл его мы не будем выгружать вообще. Удалим его сразу чтобы посмотреть объем данных.

In [18]:
data['point'] = data['point'].apply(lambda x: [x['lat'], x['long']])

In [19]:
data.drop(columns=['geometry'], inplace=True)

In [20]:
print('Объем файла',round(data.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 6.84 MB


### nearby

In [21]:
data['nearby'].apply(len).max()

343

In [22]:
data.explode('nearby')['nearby'].nunique()

1746

In [23]:
data.explode('nearby')['nearby'].unique()

array(['Жилые дома индивидуальной застройки',
       'Многоквартирные жилые дома', 'Внутридворовая территория', ...,
       '[ "Многоквартирные жилые дома", "Административные здания", "АЗС", "Автовокзал (автостанция)" ]',
       '[ "Многоквартирные жилые дома", "Нерегулируемый пешеходный переход", "Спортивные и развлекательные объекты", "Школа либо иное детское (в т.ч. дошкольное) учреждение" ]',
       '[ "Мост", "Жилые дома индивидуальной застройки", "Регулируемый ж\\/д переезд без дежурного" ]'],
      dtype=object)

Сохраним информацию о объектах находящихся рядом в отдельный датасет, а так же проведем категоризацию. Если эти данные понадобяться, то по id мы сможем их использовать.

In [24]:
data['nearby'] = data['nearby'].apply(lambda x: [elem.strip(' "[]') for elem in (ast.literal_eval(x) if not isinstance(x, list) else x)])

In [25]:
data.explode('nearby')['nearby'].nunique()
unique_values = data.explode('nearby')['nearby'].unique()
print(unique_values)

['Жилые дома индивидуальной застройки' 'Многоквартирные жилые дома'
 'Внутридворовая территория'
 'Школа либо иное детское (в т.ч. дошкольное) учреждение'
 'Административные здания' 'Остановка общественного транспорта'
 'Нерегулируемый пешеходный переход'
 'Автостоянка (отделенная от проезжей части)' 'Остановка трамвая'
 'Выезд с прилегающей территории' 'Регулируемый перекрёсток'
 'Регулируемый пешеходный переход'
 'Нерегулируемый перекрёсток неравнозначных улиц (дорог)'
 'Эстакада, путепровод' 'Регулируемый перекресток'
 'Спортивные и развлекательные объекты' 'Нерегулируемый перекрёсток'
 'Крупный торговый объект (являющийся объектом массового тяготения пешеходов и (или) транспорта)'
 'Объект строительства' 'Объект (здание, сооружение) религиозного культа'
 'АЗС'
 'Одиночный торговый объект, являющийся местом притяжения транспорта и (или) пешеходов'
 'Регулируемый ж/д переезд без дежурного' 'Производственное предприятие'
 'Иная образовательная организация'
 'Школа либо иная детская (в

У нас получилось 62 уникальных объектов, в других файлах их может быть еще больше. Поэтому мы сделаем 15 разных категорий, и все что в них не попадет, назовем - другое.   

Категории:
* Жилая застройка:
  - Индивидуальная застройка
  - Многоквартирные дома

* Образовательные учреждения:
  - Школы
  - Детские (в т.ч. дошкольные) учреждения

* Административные здания

* Транспортная инфраструктура:
  - Остановки общественного транспорта
  - Автостоянки
  - Транспортные перекрестки
  - Ж/д переезды
  - Переправы
  - Тоннели
  - Пункты весового контроля

* Развлекательные и спортивные объекты

* Торговые объекты:

* Религиозные сооружения

* Медицинские учреждения

* Объекты строительства

* Производственные предприятия

* Зоны отдыха

* Транспортные узлы:
  - Аэропорты
  - Ж/д вокзалы
  - Речные или морские порты

* Пешеходная инфраструктура:
  - Тротуары
  - Пешеходные дорожки
  - Пешеходные зоны
  - Пешеходные переходы

* Службы безопасности:
  - СП ДПС (КПМ)
  - Территориальные подразделения МВД России

* Другие объекты:
  - Кладбища
  - Места для перегона скота
  - И другое

In [26]:
nearby_dictionary = {
    'Жилые дома индивидуальной застройки': 'Жилая застройка',
    'Многоквартирные жилые дома': 'Жилая застройка',
    'Внутридворовая территория': 'Жилая застройка',
    'Школа либо иное детское (в т.ч. дошкольное) учреждение': 'Образовательные учреждения',
    'Административные здания': 'Административные здания',
    'Остановка общественного транспорта': 'Транспортная инфраструктура',
    'Нерегулируемый пешеходный переход': 'Пешеходная инфраструктура',
    'Регулируемый пешеходный переход': 'Пешеходная инфраструктура',
    'Автостоянка (отделенная от проезжей части)': 'Транспортная инфраструктура',
    'Остановка трамвая': 'Транспортная инфраструктура',
    'Выезд с прилегающей территории': 'Транспортная инфраструктура',
    'Регулируемый перекрёсток': 'Транспортная инфраструктура',
    'Нерегулируемый перекрёсток неравнозначных улиц (дорог)': 'Транспортная инфраструктура',
    'Эстакада, путепровод': 'Транспортная инфраструктура',
    'Спортивные и развлекательные объекты': 'Развлекательные объекты',
    'Крупный торговый объект (являющийся объектом массового тяготения пешеходов и (или) транспорта)': 'Торговые объекты',
    'Объект строительства': 'Строительные объекты',
    'Объект (здание, сооружение) религиозного культа': 'Религиозные сооружения',
    'АЗС': 'Транспортная инфраструктура',
    'Одиночный торговый объект, являющийся местом притяжения транспорта и (или) пешеходов': 'Торговые объекты',
    'Регулируемый ж/д переезд без дежурного': 'Транспортная инфраструктура',
    'Производственное предприятие': 'Промышленные объекты',
    'Иная образовательная организация': 'Образовательные учреждения',
    'Мост': 'Транспортная инфраструктура',
    'Медицинские (лечебные) организации': 'Медицинские учреждения',
    'Автостоянка (не отделённая от проезжей части)': 'Транспортная инфраструктура',
    'Нерегулируемый перекрёсток равнозначных улиц (дорог)': 'Транспортная инфраструктура',
    'Подземный пешеходный переход': 'Пешеходная инфраструктура',
    'Кладбище': 'Религиозные сооружения',
    'Тротуар, пешеходная дорожка': 'Пешеходная инфраструктура',
    'Пешеходная зона': 'Пешеходная инфраструктура',
    'Остановка маршрутного такси': 'Транспортная инфраструктура',
    'Лечебные учреждения': 'Медицинские учреждения',
    'Объект торговли, общественного питания на автодороге вне НП': 'Торговые объекты',
    'Нерегулируемый ж/д переезд': 'Транспортная инфраструктура',
    'Ледовая переправа (официально открытая и оборудованная);': 'Транспортная инфраструктура',
    'СП ДПС (КПМ)': 'Службы безопасности',
    'Иное образовательное учреждение': 'Образовательные учреждения',
    'Территориальное подразделение МВД России (либо его структурное подразделение)': 'Службы безопасности',
    'Автовокзал (автостанция)': 'Транспортная инфраструктура',
    'Нерегулируемый пешеходный переход, расположенный на участке улицы или дороги, проходящей вдоль территории школы или иной детской организации': 'Пешеходная инфраструктура',
    'Нерегулируемое пересечение с круговым движением': 'Транспортная инфраструктура',
    'Мост, эстакада, путепровод': 'Транспортная инфраструктура',
    'Зоны отдыха': 'Зоны отдыха',
    'Аэропорт, ж/д вокзал (ж/д станция), речной или морской порт (пристань)': 'Транспортная инфраструктура',
    'Подход к мосту, эстакаде, путепроводу': 'Транспортная инфраструктура',
    'Регулируемый ж/д переезд с дежурным': 'Транспортная инфраструктура',
    'Надземный пешеходный переход': 'Пешеходная инфраструктура',
    'Нерегулируемый перекрёсток равнозначных улиц (дорог)': 'Транспортная инфраструктура',
    'Кладбище': 'Религиозные сооружения',
    'Тротуар, пешеходная дорожка': 'Пешеходная инфраструктура',
    'Пешеходная зона': 'Пешеходная инфраструктура',
    'Остановка маршрутного такси': 'Транспортная инфраструктура',
    'Лечебные учреждения': 'Медицинские учреждения',
    'Объект торговли, общественного питания на автодороге вне НП': 'Торговые объекты',
    'Нерегулируемый ж/д переезд': 'Транспортная инфраструктура',
    'Ледовая переправа (официально открытая и оборудованная);': 'Транспортная инфраструктура',
    'СП ДПС (КПМ)': 'Службы безопасности',
    'Иное образовательное учреждение': 'Образовательные учреждения',
    'Территориальное подразделение МВД России (либо его структурное подразделение)': 'Службы безопасности',
    'Автовокзал (автостанция)': 'Транспортная инфраструктура',
    'Регулируемый пешеходный переход, расположенный на участке улицы или дороги, проходящей вдоль территории школы или иной детской организации': 'Пешеходная инфраструктура',
    'Нерегулируемый пешеходный переход, расположенный на участке улицы или дороги, проходящей вдоль территории школы или иного детского учреждения': 'Пешеходная инфраструктура',
    'Регулируемый пешеходный переход, расположенный на участке улицы или дороги, проходящей вдоль территории школы или иного детского учреждения': 'Пешеходная инфраструктура',
    'Нерегулируемый перекрёсток  ': 'Транспортная инфраструктура',
    'Место для перегона скота': 'Другие объекты',
    'Нерегулируемое пересечение с круговым движением   ': 'Транспортная инфраструктура',
    'Пункт весового контроля': 'Транспортная инфраструктура',
    'Тоннель': 'Транспортная инфраструктура'
}

In [27]:
# пишем функцию, которая заменит все значения в соответствии со словарем
def replace_values(lst):
    replaced_lst = [nearby_dictionary.get(item, "Другие объекты") for item in lst]
    unique_values = list(set(replaced_lst))
    unique_values.sort()  # Сортировка списка по алфавиту
    return unique_values

# Применяем функцию к каждому элементу DataFrame
data['nearby'] = data['nearby'].map(replace_values)

In [28]:
# избавляемся от списка
data['nearby']=data['nearby'].apply(lambda x: ', '.join(x))

In [29]:
data['nearby'].apply(lambda x: len(x.split(', '))).max()


6

In [30]:
print('Объем файла',round(data.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 6.84 MB


Мы создали отельный файл, который можно вызвать по надобности, из основного файла мы удалили эту информацию. Файл стал весить меньше, 6.48 MB.

### region

In [31]:
data['region'].unique()

array(['Барнаул', 'Немецкий национальный район', 'Шипуновский район',
       'Чарышский район', 'Целинный район', 'Хабарский район',
       'Усть-Пристанский район', 'Усть-Калманский район',
       'Угловский район', 'Тюменцевский район', 'Троицкий район',
       'Третьсяковский район', 'Топчихинский район', 'Тогульский район',
       'Тальменский район', 'Табунский район', 'Шелаболихинский район',
       'Солтонский район', 'Солонешенский район', 'Советский район',
       'Суетский район', 'Славгородский район', 'Романовский район',
       'Родинский район', 'Ребрихинский район', 'Поспелихинский район',
       'Петропавловский район', 'Панкрушихинский район',
       'Павловский район', 'Зональный район', 'Новичихинский район',
       'Михайловский район', 'Мамонтовский район', 'Локтевский район',
       'Кытмановский район', 'Курьинский район', 'Кулундинский район',
       'Крутихинский район', 'Краснощековский район',
       'Красногорский район', 'Косихинский район', 'Ключевский рай

In [32]:
print('Объем файла',round(data.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 6.84 MB


Столбец с регионом оставляем без изменений, если он нам не пригодиться удалим его из конечного файла.

### scheme


In [33]:
data['scheme'].unique()

array(['830', '880', '960', '130', '500', '210', '730', '200', '740',
       '070', '810', '300', '090', '970', '600', '710', None, '040',
       '820', '850', '770', '940', '910', '720', '030', '700', '430',
       '140', '420', '110', '610', '330', '800', '440', '920', '190',
       '930', '780', '760', '410', '060', '840', '750', '860', '220',
       '400', '950', '870', '340', '120', '050', '010', '900', '100',
       '980', '620', '310', '020', '320', '630', '230'], dtype=object)

Возможно удалим, пока не знаю. Схема дтп, что-то не понятное. Удаляем!

In [34]:
data.drop('scheme', axis=1, inplace=True)


In [35]:
print('Объем файла',round(data.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 6.48 MB


### address

In [36]:
data['address'].unique()

array([None, 'г Барнаул, ул Сиреневая, 11', 'г Барнаул, ул Попова, 165',
       ..., 'г Алексеевка, ул Маяковского, 121',
       'г Алексеевка, ул Мостовая, 153',
       'а/д Валуйки-Алексеевка-Красное, 64 км'], dtype=object)

Адрес, удаляем.

In [37]:
data.drop('address', axis=1, inplace=True)


In [38]:
print('Объем файла',round(data.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 6.11 MB


### weather

In [39]:
 list(data.explode('weather')['weather'].unique())

['Ясно',
 'Пасмурно',
 'Снегопад',
 'Дождь',
 'Температура ниже -30С',
 'Метель',
 'Температура выше +30С',
 'Ураганный ветер',
 'Туман']

In [40]:
data['weather'].apply(len).max()

2

In [41]:
expanded_weather = data['weather'].explode()

# Подсчитать количество уникальных значений
weather_counts = expanded_weather.value_counts()
weather_counts

weather
Ясно                     29983
Пасмурно                 12981
Снегопад                  2618
Дождь                     2549
Метель                     498
Туман                      259
Температура выше +30С      216
Температура ниже -30С      106
Ураганный ветер             47
Name: count, dtype: int64

Для погоды оставим только слудующие показатели: Ясно и Пасмурно - эти 2 показателя занимают большую часть датасета. Если в строке нет ни Ясно ни Пасмурно, строку заполним Другая.

In [42]:
data['weather']=data['weather'].apply(lambda x: ','.join(x))

In [43]:
def process_weather(row):
    if 'Ясно' in row:
        return 'Ясно'
    elif 'Пасмурно' in row:
        return 'Пасмурно'
    else:
        return 'Другое'

# Применяем функцию к столбцу
data['weather'] = data['weather'].apply(process_weather)

In [44]:
data['weather'].unique()

array(['Ясно', 'Пасмурно', 'Другое'], dtype=object)

In [45]:
print('Объем файла',round(data.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 6.11 MB


### category

In [46]:
data['category'].unique()

array(['Наезд на пешехода', 'Иной вид ДТП', 'Падение пассажира',
       'Столкновение', 'Наезд на велосипедиста', 'Съезд с дороги',
       'Наезд на препятствие', 'Наезд на стоящее ТС', 'Опрокидывание',
       'Наезд на животное',
       'Наезд на лицо, не являющееся участником дорожного движения, осуществляющее производство работ',
       'Отбрасывание предмета',
       'Наезд на лицо, не являющееся участником дорожного движения, осуществляющее несение службы',
       'Наезд на лицо, не являющееся участником дорожного движения, осуществляющее какую-либо другую деятельность',
       'Наезд на внезапно возникшее препятствие',
       'Наезд на гужевой транспорт',
       'Возгорание вследствие технической неисправности движущегося или остановившегося ТС, участвующего в дорожном движении.',
       'Падение груза'], dtype=object)

Здесь все отлично, ничего изменять не будем.

### datetime

In [47]:
data['datetime'].unique()

<DatetimeArray>
['2023-05-24 19:30:00', '2015-09-16 13:00:00', '2017-08-25 15:30:00',
 '2021-05-29 19:40:00', '2021-05-25 16:40:00', '2021-02-22 13:50:00',
 '2022-12-01 11:50:00', '2017-12-15 21:48:00', '2022-10-11 17:15:00',
 '2022-10-08 21:00:00',
 ...
 '2018-05-20 12:55:00', '2018-03-03 11:00:00', '2018-03-05 22:45:00',
 '2016-07-01 01:35:00', '2019-02-15 14:25:00', '2019-02-17 18:00:00',
 '2017-12-11 09:30:00', '2017-09-26 19:15:00', '2019-01-19 20:00:00',
 '2019-07-17 20:43:00']
Length: 46327, dtype: datetime64[ns]

In [48]:
data['date'] = data['datetime'].dt.date
data['time'] = data['datetime'].dt.time

In [49]:
data.drop('datetime', axis=1, inplace=True)
print('Объем файла',round(data.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 6.48 MB


### severity

In [50]:
data['severity'].unique()

array(['Легкий', 'Тяжёлый', 'С погибшими'], dtype=object)

###  vehicles

In [51]:
data['vehicles'].apply(len).max()

10250

In [52]:
# Функция для извлечения информации о машине и водителях
def extract_driver_info(row):
    data = json.loads(row['vehicles'])
    drivers_info = []
    for car in data:
        car_id = row['id']
        for participant in car.get("participants", []):
            if participant.get("role") == "Водитель":
                result = {
                    "id": car_id,
                    "year": car.get("year"),
                    "brand": car.get("brand"),
                    "color": car.get("color"),
                    "model": car.get("model"),
                    "category": car.get("category"),
                    "driver_gender": participant.get("gender"),
                    "driver_violations": participant.get("violations"),
                    "driver_years_of_driving_experience": participant.get("years_of_driving_experience")
                }
                drivers_info.append(result)
    return drivers_info

# Применяем функцию к DataFrame и сохраняем результаты в новый DataFrame
drivers_info_series = data.apply(extract_driver_info, axis=1)
drivers_info_df = pd.DataFrame([item for sublist in drivers_info_series for item in sublist])


In [53]:
drivers_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70155 entries, 0 to 70154
Data columns (total 9 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   id                                  70155 non-null  int64  
 1   year                                68638 non-null  float64
 2   brand                               68632 non-null  object 
 3   color                               68935 non-null  object 
 4   model                               68632 non-null  object 
 5   category                            70155 non-null  object 
 6   driver_gender                       68278 non-null  object 
 7   driver_violations                   70155 non-null  object 
 8   driver_years_of_driving_experience  61496 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 4.8+ MB


In [54]:
pd.set_option('display.max_colwidth', None)

drivers_info_df.head()

id    year            brand         color                     model  \
0  2869171  2015.0  Прочие марки ТС        Черный  Прочие марки и модели ТС   
1  2320091  2002.0           TOYOTA         Серый                   Corolla   
2  2321011  1981.0          DAIMLER  Многоцветный     Прочие модели DAIMLER   
3  2576909  2001.0            HONDA         Серый                    Torneo   
4  2576909  1987.0            HONDA         Синий                     Magna   

                                                     category driver_gender  \
0  Мопеды с двигателем внутреннего сгорания менее 50 см. куб.       Мужской   
1                С-класс (малый средний, компактный) до 4,3 м       Мужской   
2                             Одноэтажные длиной от 8 до 12 м       Мужской   
3                                    В-класс (малый) до 3,9 м       Женский   
4                                                   Мотоциклы       Мужской   

                                                                                                                                                                              driver_violations  \
0  [Управление мопедом лицом моложе 16 лет, Управление ТС лицом, не имеющим права на управление ТС, Оставление места ДТП, Невыполнение требований обеспечения безопасности при начале движения]   
1                                                                                                                          [Несоблюдение условий, разрешающих движение транспорта задним ходом]   
2                                                                                                                                                                                            []   
3                                                                                                                                                            [Несоблюдение очередности проезда]   
4                                                                                                                                                                                            []   

   driver_years_of_driving_experience  
0                                 NaN  
1                                14.0  
2                                25.0  
3                                 5.0  
4                                 7.0

In [55]:
data.drop('vehicles', axis=1, inplace=True)
print('Объем файла',round(data.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 6.11 MB


### dead_count

In [56]:
data['dead_count'].unique()

array([ 0,  1,  2,  4,  3,  5,  8,  6,  9, 11])

In [57]:
data['dead_count']=data['dead_count'].astype('int16')

### participants

In [58]:
pd.set_option('display.max_colwidth', None)

data['participants'].head(5)

0    [ { "role": "Пешеход", "gender": "Мужской", "violations": [ ], "health_status": "Раненый, находящийся (находившийся) на амбулаторном лечении, либо в условиях дневного стационара" } ]
1                                                                                                                                                                                       [ ]
2                                                                                                                                                                                       [ ]
3                                                                                                                                                                                       [ ]
4                                                                                                                                                                                       [ ]
Name: participants, dtype: object

In [59]:
# Функция для извлечения информации о каждом участнике
def extract_participant_info(row):
    participants_data = json.loads(row['participants'])
    participants_info = []
    for participant in participants_data:
        result = {
            "id": row['id'],
            "role": participant.get("role"),
            "gender": participant.get("gender"),
            "violations": participant.get("violations"),
            "health_status": participant.get("health_status")
        }
        participants_info.append(result)
    return participants_info

# Применяем функцию к DataFrame и сохраняем результаты в новый DataFrame
participants_info_series = data.apply(extract_participant_info, axis=1)
participants_info_df = pd.DataFrame([item for sublist in participants_info_series for item in sublist])


In [60]:
participants_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15651 entries, 0 to 15650
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   id             15651 non-null  int64 
 1   role           15651 non-null  object
 2   gender         15379 non-null  object
 3   violations     15651 non-null  object
 4   health_status  15651 non-null  object
dtypes: int64(1), object(4)
memory usage: 611.5+ KB


In [61]:
pd.set_option('display.max_colwidth', None)

participants_info_df.head()

id     role   gender violations  \
0  2869171  Пешеход  Мужской         []   
1  2801648  Пешеход  Женский         []   
2  2771096  Пешеход  Женский         []   
3  2771105  Пешеход  Женский         []   
4  2313364  Пешеход  Мужской         []   

                                                                                                                                                                                                health_status  
0                                                                                                            Раненый, находящийся (находившийся) на амбулаторном лечении, либо в условиях дневного стационара  
1                                                                                                            Раненый, находящийся (находившийся) на амбулаторном лечении, либо в условиях дневного стационара  
2                                                                                                                                                 Раненый, находящийся (находившийся) на стационарном лечении  
3                                                                                                            Раненый, находящийся (находившийся) на амбулаторном лечении, либо в условиях дневного стационара  
4  Раненый, находящийся (находившийся)  на амбулаторном лечении, либо которому по характеру полученных травм обозначена необходимость амбулаторного лечения (вне зависимости от его фактического прохождения)

In [62]:
data.drop('participants', axis=1, inplace=True)
print('Объем файла',round(data.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 5.47 MB


### injured_count

In [63]:
data['injured_count'].unique()

array([ 1,  3,  0,  2,  4,  5,  7,  6, 12, 23,  8,  9, 14, 10, 11, 34, 17,
       18, 13, 15])

In [64]:
data['injured_count']=data['injured_count'].astype('int16')

### parent_region

In [65]:
data['parent_region'].unique()

array(['Алтайский край', 'Амурская область', 'Белгородская область'],
      dtype=object)

### road_conditions

In [66]:
data['road_conditions'].apply(len).max()

5

In [67]:
 list(data.explode('road_conditions')['road_conditions'].unique())

['Сухое',
 'Отсутствие, плохая различимость горизонтальной разметки проезжей части',
 'Неправильное применение, плохая видимость дорожных знаков',
 'Обработанное противогололедными материалами',
 'Иные недостатки',
 'Отсутствие элементов обустройства остановочного пункта общественного пассажирского транспорта',
 'Отсутствие дорожных знаков в необходимых местах',
 'Недостатки зимнего содержания',
 'Со снежным накатом',
 'Недостаточное освещение',
 'Заснеженное',
 'Отсутствие пешеходных ограждений в необходимых местах',
 'Мокрое',
 'Дефекты покрытия',
 'Неисправное освещение',
 'Отсутствие освещения',
 'Отсутствие дорожных ограждений в необходимых местах',
 'Неисправность светофора',
 'Отсутствие временных ТСОД в местах проведения работ',
 'Отсутствие тротуаров (пешеходных дорожек)',
 'Гололедица',
 'Отклонение верха головки рельса трамвайных (железнодорожных) путей, расположенных в пределах проезжей части, относительно покрытия, более чем на 2,0 см',
 'Плохая видимость светофора',
 'Отс

In [68]:

# Функция для извлечения состояния покрытия дороги и отсутствия элементов безопасности
def extract_road_conditions(conditions_list):
    road_surface_conditions = [
        'Сухое', 'Обработанное противогололедными материалами', 'Со снежным накатом', 'Заснеженное',
        'Мокрое', 'Гололедица', 'Загрязненное', 'Пыльное', 'Залитое (покрытое) водой',
        'Плохая различимость горизонтальной разметки проезжей части', 
        'Плохая различимость вертикальной разметки', 'Неровное покрытие', 
        'Низкие сцепные качества покрытия'
    ]
    
    road_lack_safety_features_conditions = [
        'Отсутствие дорожных знаков в необходимых местах', 'Отсутствие дорожных ограждений в необходимых местах',
        'Отсутствие пешеходных ограждений в необходимых местах', 'Отсутствие освещения',
        'Неудовлетворительное состояние обочин', 'Отсутствие тротуаров (пешеходных дорожек)',
        'Отсутствие временных ТСОД в местах проведения работ', 
        'Отсутствие, плохая различимость горизонтальной разметки проезжей части',
        'Несоответствие дорожных ограждений предъявляемым требованиям'
    ]
    
    road_surface = ', '.join([condition for condition in conditions_list if condition in road_surface_conditions])
    road_lack_safety_features = ', '.join([condition for condition in conditions_list if condition in road_lack_safety_features_conditions])
    
    if not road_surface:
        road_surface = 'Другое'
    
    if not road_lack_safety_features:
        road_lack_safety_features = 'Другое'
    
    return pd.Series({
        'road_surface': road_surface,
        'road_lack_safety_features': road_lack_safety_features
    })

# Применяем функцию к DataFrame и сохраняем результаты в новых столбцах
extracted_conditions = data['road_conditions'].apply(extract_road_conditions)
data = pd.concat([data, extracted_conditions], axis=1)


In [69]:
data.drop('road_conditions', axis=1, inplace=True)
print('Объем файла',round(data.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 5.56 MB


### participants_count

In [70]:
data['participants_count'].unique()

array([ 2,  3,  4,  1,  7,  6,  5,  9,  8, 13, 11, 15, 24, 10, 16, 17, 36,
       23, 38, 14, 12, 20, 25, 21])

In [71]:
data['participants_count']=data['participants_count'].astype('int16')

### participant_categories

In [72]:
data['participant_categories'].head()

0    [Все участники, Пешеходы, Мотоциклисты]
1                      [Дети, Все участники]
2                      [Дети, Все участники]
3              [Мотоциклисты, Все участники]
4                            [Все участники]
Name: participant_categories, dtype: object

In [73]:
data['participant_categories'].apply(len).max()

4

In [74]:
 list(data.explode('participant_categories')['participant_categories'].unique())

['Все участники',
 'Пешеходы',
 'Мотоциклисты',
 'Дети',
 'Велосипедисты',
 'Общ. транспорт']

In [75]:
expanded_weather = data['participant_categories'].explode()

# Подсчитать количество уникальных значений
weather_counts = expanded_weather.value_counts()
weather_counts

participant_categories
Все участники     47820
Пешеходы          14850
Дети               5180
Мотоциклисты       3339
Велосипедисты      1603
Общ. транспорт      532
Name: count, dtype: int64

In [76]:
# Функция для извлечения категорий участников
def extract_participant_categories(categories_list):
    all_participants = 'Все участники' in categories_list
    pedestrians = 'Пешеходы' in categories_list
    motorcyclists = 'Мотоциклисты' in categories_list
    children = 'Дети' in categories_list
    
    return pd.Series({
        'all_participants': int(all_participants),
        'pedestrians': int(pedestrians),
        'motorcyclists': int(motorcyclists),
        'children': int(children)
    }).astype('int16')

# Применяем функцию к DataFrame и сохраняем результаты в новых столбцах
extracted_categories = data['participant_categories'].apply(extract_participant_categories)
data = pd.concat([data, extracted_categories], axis=1)


In [77]:
data.head()

id  tags                light                   point  \
0  2869171     1  Светлое время суток      [53.3912, 83.7879]   
1  2320091    12  Светлое время суток  [53.345833, 83.666389]   
2  2321011    12  Светлое время суток    [53.19706, 83.39688]   
3  2576909     1  Светлое время суток      [53.3764, 83.7142]   
4  2575209     1  Светлое время суток  [53.343071, 83.794366]   

                                                                            nearby  \
0                                                                  Жилая застройка   
1                                      Жилая застройка, Образовательные учреждения   
2  Административные здания, Пешеходная инфраструктура, Транспортная инфраструктура   
3  Административные здания, Пешеходная инфраструктура, Транспортная инфраструктура   
4          Жилая застройка, Пешеходная инфраструктура, Транспортная инфраструктура   

    region   weather           category severity  dead_count  injured_count  \
0  Барнаул      Ясно  Наезд на пешехода   Легкий           0              1   
1  Барнаул  Пасмурно       Иной вид ДТП   Легкий           0              1   
2  Барнаул      Ясно  Падение пассажира   Легкий           0              1   
3  Барнаул      Ясно       Столкновение  Тяжёлый           0              1   
4  Барнаул      Ясно       Столкновение   Легкий           0              1   

    parent_region  participants_count  \
0  Алтайский край                   2   
1  Алтайский край                   2   
2  Алтайский край                   3   
3  Алтайский край                   3   
4  Алтайский край                   2   

                    participant_categories        date      time road_surface  \
0  [Все участники, Пешеходы, Мотоциклисты]  2023-05-24  19:30:00        Сухое   
1                    [Дети, Все участники]  2015-09-16  13:00:00        Сухое   
2                    [Дети, Все участники]  2017-08-25  15:30:00        Сухое   
3            [Мотоциклисты, Все участники]  2021-05-29  19:40:00        Сухое   
4                          [Все участники]  2021-05-25  16:40:00        Сухое   

                                                road_lack_safety_features  \
0                                                                  Другое   
1                                                                  Другое   
2                                                                  Другое   
3  Отсутствие, плохая различимость горизонтальной разметки проезжей части   
4  Отсутствие, плохая различимость горизонтальной разметки проезжей части   

   all_participants  pedestrians  motorcyclists  children  
0                 1            1              1         0  
1                 1            0              0         1  
2                 1            0              0         1  
3                 1            0              1         0  
4                 1            0              0         0

In [78]:
data.drop('participant_categories', axis=1, inplace=True)
print('Объем файла',round(data.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 5.29 MB


In [79]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47820 entries, 0 to 47819
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   id                         47820 non-null  int32 
 1   tags                       47820 non-null  int16 
 2   light                      47820 non-null  object
 3   point                      47820 non-null  object
 4   nearby                     47820 non-null  object
 5   region                     47820 non-null  object
 6   weather                    47820 non-null  object
 7   category                   47820 non-null  object
 8   severity                   47820 non-null  object
 9   dead_count                 47820 non-null  int16 
 10  injured_count              47820 non-null  int16 
 11  parent_region              47820 non-null  object
 12  participants_count         47820 non-null  int16 
 13  date                       47820 non-null  object
 14  time  

## Преобразование 1

Попробуем написать функцию, которая будет преобразовывать наш файл сразу. Получится один главнфй файл data, файл с df_nearby, drivers_info_df и participants_info_df. 

In [80]:
dk=gpd.read_file('/Users/juliagrebeneva/Desktop/test/belgorodskaia-oblast.geojson')
dk = dk.drop(columns=['geometry', 'scheme', 'address'])


In [81]:
dk.head()

id                                 tags                light  \
0  2700162  [Дорожно-транспортные происшествия]  Светлое время суток   
1  1579673  [Дорожно-транспортные происшествия]  Светлое время суток   
2  1580488  [Дорожно-транспортные происшествия]  Светлое время суток   
3  1584118  [Дорожно-транспортные происшествия]  Светлое время суток   
4  2500365  [Дорожно-транспортные происшествия]  Светлое время суток   

                                   point  \
0  {'lat': 50.581711, 'long': 36.546707}   
1      {'lat': 50.5989, 'long': 36.5303}   
2  {'lat': 50.565494, 'long': 36.561309}   
3      {'lat': 50.6008, 'long': 36.6011}   
4  {'lat': 50.599488, 'long': 36.632946}   

                                                                                                                                                                                      nearby  \
0                                                                                                                            [Жилые дома индивидуальной застройки, Регулируемый перекресток]   
1                                                                                                                                                               [Мост, эстакада, путепровод]   
2                                                                                                 [Многоквартирные жилые дома, Остановка общественного транспорта, Регулируемый перекресток]   
3  [Многоквартирные жилые дома, Остановка общественного транспорта, Нерегулируемый пешеходный переход, Одиночный торговый объект, являющийся местом притяжения транспорта и (или) пешеходов]   
4                                                                                                                               [Административные здания, Нерегулируемый пешеходный переход]   

     region     weather           category            datetime     severity  \
0  Белгород      [Ясно]       Столкновение 2022-05-14 16:30:00      Тяжёлый   
1  Белгород  [Снегопад]       Столкновение 2017-12-24 12:35:00       Легкий   
2  Белгород      [Ясно]       Столкновение 2019-11-26 11:05:00       Легкий   
3  Белгород      [Ясно]  Падение пассажира 2016-11-29 09:05:00       Легкий   
4  Белгород      [Ясно]  Наезд на пешехода 2020-10-20 08:00:00  С погибшими   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        vehicles  \
0                                                                                                   [ { "year": 2009, "brand": "ВАЗ", "color": "Серый", "model": "ВАЗ 2114 и модификации", "category": "Прочие легковые автомобили", "participants": [ { "role": "Водитель", "gender": "Мужской", "violations": [ "Неправильный выбор дистанции", "Управление транспортным средством при наличии неисправностей или условий, при которых эксплуатация транспортного средства запрещена" ], "health_status": "Не пострадал", "years_of_driving_experience": 7 } ] }, { "year": 2007, "brand": "ВАЗ", "color": "Серый", "model": "ВАЗ 2114 и модификации", "category": "В-класс (малый) до 3,9 м

In [82]:
dk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11236 entries, 0 to 11235
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype         
---  ------                  --------------  -----         
 0   id                      11236 non-null  int64         
 1   tags                    11236 non-null  object        
 2   light                   11236 non-null  object        
 3   point                   11236 non-null  object        
 4   nearby                  11236 non-null  object        
 5   region                  11236 non-null  object        
 6   weather                 11236 non-null  object        
 7   category                11236 non-null  object        
 8   datetime                11236 non-null  datetime64[ns]
 9   severity                11236 non-null  object        
 10  vehicles                11236 non-null  object        
 11  dead_count              11236 non-null  int64         
 12  participants            11236 non-null  object

In [83]:
print('Объем файла',round(dk.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 1.54 MB


In [84]:

def copy(dk):

    dk['id'] = dk['id'].astype('int32')
    dk['dead_count'] = dk['dead_count'].astype('int16')
    dk['injured_count'] = dk['injured_count'].astype('int16')
    dk['participants_count'] = dk['participants_count'].astype('int16')
    dk['tags'] = dk['tags'].apply(map_values).astype('int16')
    
    dk['point'] = dk['point'].apply(lambda x: [x['lat'], x['long']])
    
    dk['nearby'] = dk['nearby'].map(replace_values)
    dk['nearby']=dk['nearby'].apply(lambda x: ', '.join(x))
    
    
    dk['weather']=dk['weather'].apply(lambda x: ','.join(x))
    dk['weather'] = dk['weather'].apply(process_weather)
    
    dk['date'] = dk['datetime'].dt.date
    dk['time'] = dk['datetime'].dt.time
    dk.drop('datetime', axis=1, inplace=True)
    
    drivers_info_series = dk.apply(extract_driver_info, axis=1)
    drivers_info_df = pd.DataFrame([item for sublist in drivers_info_series for item in sublist])
    dk.drop('vehicles', axis=1, inplace=True)

    
    extracted_conditions = dk['road_conditions'].apply(extract_road_conditions)
    dk = pd.concat([dk, extracted_conditions], axis=1)
    dk.drop('road_conditions', axis=1, inplace=True)
    
    participants_info_series = dk.apply(extract_participant_info, axis=1)
    participants_info_df = pd.DataFrame([item for sublist in participants_info_series for item in sublist])
    dk.drop('participants', axis=1, inplace=True)

    extracted_categories = dk['participant_categories'].apply(extract_participant_categories)
    dk = pd.concat([dk, extracted_categories], axis=1)
    dk.drop('participant_categories', axis=1, inplace=True)

    return dk, drivers_info_df,participants_info_df



In [85]:
dk_processed, drivers_info_df_processed, participants_info_df_processed = copy(dk)


In [86]:
dk_processed.head()

id  tags                light                   point  \
0  2700162     1  Светлое время суток  [50.581711, 36.546707]   
1  1579673     1  Светлое время суток      [50.5989, 36.5303]   
2  1580488     1  Светлое время суток  [50.565494, 36.561309]   
3  1584118     1  Светлое время суток      [50.6008, 36.6011]   
4  2500365     1  Светлое время суток  [50.599488, 36.632946]   

                                                                                      nearby  \
0                                                            Другие объекты, Жилая застройка   
1                                                                Транспортная инфраструктура   
2                               Другие объекты, Жилая застройка, Транспортная инфраструктура   
3  Жилая застройка, Пешеходная инфраструктура, Торговые объекты, Транспортная инфраструктура   
4                                         Административные здания, Пешеходная инфраструктура   

     region weather           category     severity  dead_count  \
0  Белгород    Ясно       Столкновение      Тяжёлый           0   
1  Белгород  Другое       Столкновение       Легкий           0   
2  Белгород    Ясно       Столкновение       Легкий           0   
3  Белгород    Ясно  Падение пассажира       Легкий           0   
4  Белгород    Ясно  Наезд на пешехода  С погибшими           1   

   injured_count         parent_region  participants_count        date  \
0              1  Белгородская область                   3  2022-05-14   
1              1  Белгородская область                   2  2017-12-24   
2              1  Белгородская область                   2  2019-11-26   
3              1  Белгородская область                   2  2016-11-29   
4              0  Белгородская область                   2  2020-10-20   

       time                                 road_surface  \
0  16:30:00                                        Сухое   
1  12:35:00  Обработанное противогололедными материалами   
2  11:05:00                                        Сухое   
3  09:05:00                                        Сухое   
4  08:00:00                                        Сухое   

                         road_lack_safety_features  all_participants  \
0                                           Другое                 1   
1                                           Другое                 1   
2  Отсутствие дорожных знаков в необходимых местах                 1   
3                                           Другое                 1   
4                                           Другое                 1   

   pedestrians  motorcyclists  children  
0            0              0         0  
1            0              0         0  
2            0              0         0  
3            0              0         0  
4            1              0         0

In [87]:
print('Объем файла',round(dk_processed.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 1.24 MB


In [88]:
drivers_info_df_processed.head()

id    year       brand       color                          model  \
0  2700162  2009.0         ВАЗ       Серый         ВАЗ 2114 и модификации   
1  2700162  2007.0         ВАЗ       Серый         ВАЗ 2114 и модификации   
2  1579673  2005.0         ВАЗ  Иные цвета   Жигули  ВАЗ-2107 модификации   
3  1579673  2004.0         ВАЗ  Иные цвета   Жигули  ВАЗ-2107 модификации   
4  1580488  2014.0  VOLKSWAGEN  Коричневый                         Tiguan   

                     category driver_gender  \
0  Прочие легковые автомобили       Мужской   
1    В-класс (малый) до 3,9 м       Мужской   
2  Прочие легковые автомобили       Мужской   
3    В-класс (малый) до 3,9 м       Мужской   
4  Прочие легковые автомобили       Мужской   

                                                                                                                                                                                                                  driver_violations  \
0                                                               [Неправильный выбор дистанции, Управление транспортным средством при наличии неисправностей или условий, при которых эксплуатация транспортного средства запрещена]   
1                                                                                                                                                                                                                                []   
2                                                                                                                                                                                                                                []   
3  [Несоответствие скорости конкретным условиям движения, Выезд на полосу встречного движения, Управление транспортным средством при наличии неисправностей или условий, при которых эксплуатация транспортного средства запрещена]   
4                                                                                                                                                 [Выезд на полосу встречного движения, Светопропускание стекол менее нормативного]   

   driver_years_of_driving_experience  
0                                 7.0  
1                                25.0  
2                                31.0  
3                                16.0  
4                                 8.0

In [89]:
drivers_info_df_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17402 entries, 0 to 17401
Data columns (total 9 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   id                                  17402 non-null  int64  
 1   year                                17231 non-null  float64
 2   brand                               17262 non-null  object 
 3   color                               17302 non-null  object 
 4   model                               17262 non-null  object 
 5   category                            17402 non-null  object 
 6   driver_gender                       17137 non-null  object 
 7   driver_violations                   17402 non-null  object 
 8   driver_years_of_driving_experience  16207 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 1.2+ MB


In [90]:
print('Объем файла',round(drivers_info_df_processed.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 1.2 MB


In [91]:
participants_info_df_processed.head()

id     role   gender violations  \
0  2500365  Пешеход  Мужской         []   
1  1585231  Пешеход  Женский         []   
2  1582918  Пешеход     None         []   
3  2486215  Пешеход  Женский         []   
4  1584715  Пешеход  Женский         []   

                                                                                                                                                                                                health_status  
0                                                                                                                                                                                Скончался в течение 22 суток  
1  Раненый, находящийся (находившийся)  на амбулаторном лечении, либо которому по характеру полученных травм обозначена необходимость амбулаторного лечения (вне зависимости от его фактического прохождения)  
2  Раненый, находящийся (находившийся)  на амбулаторном лечении, либо которому по характеру полученных травм обозначена необходимость амбулаторного лечения (вне зависимости от его фактического прохождения)  
3                                                                                                                                                 Раненый, находящийся (находившийся) на стационарном лечении  
4                                                                                                                                                 Раненый, находящийся (находившийся) на стационарном лечении

In [92]:
participants_info_df_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3324 entries, 0 to 3323
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   id             3324 non-null   int64 
 1   role           3324 non-null   object
 2   gender         3208 non-null   object
 3   violations     3324 non-null   object
 4   health_status  3324 non-null   object
dtypes: int64(1), object(4)
memory usage: 130.0+ KB


In [93]:
print('Объем файла',round(participants_info_df_processed.memory_usage().sum() / (1024 * 1024),2),'MB')

Объем файла 0.13 MB


## Преобразование 2

In [94]:
# Записываем путь к файлам
path = '/Users/juliagrebeneva/Desktop/cards/'

# Получить список всех файлов в директории
file_names = [f for f in os.listdir(path) if f.endswith('.geojson')]

# Инициализация tqdm для отслеживания прогресса
loaded_files = []

for file_name in tqdm(file_names, desc='Loading files', unit='file'):
    # Загрузка каждого файла
    gdf = gpd.read_file(os.path.join(path, file_name))
    
    # Удаление ненужных столбцов
    columns_to_drop = ['scheme', 'address']
    gdf.drop(columns=columns_to_drop, inplace=True)
    
    # Добавление загруженного файла в список
    loaded_files.append(gdf)

concatenated_gdfs = []

with tqdm(desc='Concatenating GeoDataFrames', total=len(loaded_files)) as pbar:
    for gdf in loaded_files:
        concatenated_gdfs.append(gdf)

        # Обновление прогресса
        pbar.update(1)

# Склеивание всех GeoDataFrames
data = gpd.GeoDataFrame(pd.concat(concatenated_gdfs, ignore_index=True), crs=loaded_files[0].crs)

# Вывод информации о завершении операции
print(f'Successfully loaded and concatenated {len(file_names)} files.')


Concatenating GeoDataFrames: 100%|██████████| 85/85 [00:00<00:00, 545966.06it/s]


Successfully loaded and concatenated 85 files.


In [128]:
concatenated_gdfs = []

with tqdm(desc='Concatenating GeoDataFrames', total=len(loaded_files)) as pbar:
    for gdf in loaded_files:
        concatenated_gdfs.append(gdf)

        # Обновление прогресса
        pbar.update(1)

# Склеивание всех GeoDataFrames
da = gpd.GeoDataFrame(pd.concat(concatenated_gdfs, ignore_index=True), crs=loaded_files[0].crs)

Concatenating GeoDataFrames: 100%|███████████| 85/85 [00:00<00:00, 99529.83it/s]


In [129]:
#data.to_csv('/Users/juliagrebeneva/Desktop/data.csv', index=False)


In [130]:
da.head()

id                                 tags  \
0  2921076  [Дорожно-транспортные происшествия]   
1  2442272  [Дорожно-транспортные происшествия]   
2  2434809  [Дорожно-транспортные происшествия]   
3  2434807  [Дорожно-транспортные происшествия]   
4  2434806  [Дорожно-транспортные происшествия]   

                                      light  \
0                       Светлое время суток   
1  В темное время суток, освещение включено   
2                       Светлое время суток   
3                       Светлое время суток   
4                       Светлое время суток   

                                   point  \
0  {'lat': 47.273191, 'long': 39.728757}   
1      {'lat': 47.2867, 'long': 39.7442}   
2      {'lat': 47.2544, 'long': 39.7711}   
3      {'lat': 47.2267, 'long': 39.6728}   
4      {'lat': 47.2608, 'long': 39.7683}   

                                                                    nearby  \
0  [Регулируемый пешеходный переход, Спортивные и развлекательные объекты]   
1                                             [Многоквартирные жилые дома]   
2                 [Школа либо иное детское (в т.ч. дошкольное) учреждение]   
3                                                                       []   
4       [Остановка общественного транспорта, Надземный пешеходный переход]   

           region     weather             category            datetime  \
0  Ростов-на-Дону      [Ясно]         Столкновение 2023-11-05 09:05:00   
1  Ростов-на-Дону  [Пасмурно]  Наезд на стоящее ТС 2018-05-25 20:35:00   
2  Ростов-на-Дону      [Ясно]    Наезд на пешехода 2016-09-06 14:00:00   
3  Ростов-на-Дону      [Ясно]         Столкновение 2016-09-06 07:20:00   
4  Ростов-на-Дону      [Ясно]    Наезд на пешехода 2016-09-06 06:40:00   

      severity  \
0  С погибшими   
1       Легкий   
2       Легкий   
3       Легкий   
4       Легкий   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                vehicles  \
0                                                                                                                                                                                                                                             [ { "year": 2019, "brand": "ГАЗ", "color": "Белый", "model": "Прочие модели ГАЗ", "category": "Прочая спецтехника", "participants": [ { "role": "Водитель", "gender": "Мужской", "violations": [ "Неправильный выбор дистанции", "Несоблюдение требований ОСАГО" ], "health_status": "Не пострадал", "years_of_driving_experience": 3 } ] }, { "year": 2014, "brand": "ВАЗ", "color": "Белый", "model": "Largus (Ларгус)", "category": "Прочие легковые автомобили", "participants": [ { "role": "Пассажир", "gender": "Женский", "violations": [ ], "health_status": "Получил телесные повреждения с показанием к лечению в медицинских организациях (кроме разовой медицинской помощи)", "years_of_driving_experience": null }, { "role": "Водитель", "gender": "Мужской", "violations": [ ], "health_status": "Сконча

In [131]:
da.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1411646 entries, 0 to 1411645
Data columns (total 19 columns):
 #   Column                  Non-Null Count    Dtype         
---  ------                  --------------    -----         
 0   id                      1411646 non-null  int64         
 1   tags                    1411646 non-null  object        
 2   light                   1411646 non-null  object        
 3   point                   1411646 non-null  object        
 4   nearby                  1411646 non-null  object        
 5   region                  1411646 non-null  object        
 6   weather                 1411646 non-null  object        
 7   category                1411646 non-null  object        
 8   datetime                1411646 non-null  datetime64[ns]
 9   severity                1411646 non-null  object        
 10  vehicles                1411646 non-null  object        
 11  dead_count              1411646 non-null  int64         
 12  partic

9 минут

In [132]:
def copy(dk):
    print("Start of copy function")
    
    # Преобразование типов данных
    print("Converting data types...")
    dk['id'] = dk['id'].astype('int32')
    dk['dead_count'] = dk['dead_count'].astype('int16')
    dk['injured_count'] = dk['injured_count'].astype('int16')
    dk['participants_count'] = dk['participants_count'].astype('int16')
    print("Converting data types.tags..")
    dk['tags'] = dk['tags'].apply(map_values)#.astype('int16')
    
    # Преобразование столбца point
    print("Transforming 'point' column...")
    dk['point'] = dk['point'].apply(lambda x: [x['lat'], x['long']])
    
    # Преобразование столбца nearby
    print("Transforming 'nearby' column...")
    dk['nearby'] = dk['nearby'].map(replace_values)
    dk['nearby'] = dk['nearby'].apply(lambda x: ', '.join(x))
    
    # Обработка столбца weather
    print("Processing 'weather' column...")
    dk['weather'] = dk['weather'].apply(lambda x: ','.join(x))
    dk['weather'] = dk['weather'].apply(process_weather)
    
    # Преобразование столбца datetime
    print("Processing 'datetime' column...")
    dk['date'] = dk['datetime'].dt.date
    dk['time'] = dk['datetime'].dt.time
    dk.drop('datetime', axis=1, inplace=True)
    
    # Обработка водителей
    print("Extracting driver information...")
    drivers_info_series = dk.apply(extract_driver_info, axis=1)
    drivers_info_df = pd.DataFrame([item for sublist in drivers_info_series for item in sublist])
    dk.drop('vehicles', axis=1, inplace=True)
    
    # Обработка условий дороги
    print("Extracting road conditions...")
    extracted_conditions = dk['road_conditions'].apply(extract_road_conditions)
    dk = pd.concat([dk, extracted_conditions], axis=1)
    dk.drop('road_conditions', axis=1, inplace=True)
    
    # Обработка информации о участниках
    print("Extracting participant information...")
    participants_info_series = dk.apply(extract_participant_info, axis=1)
    participants_info_df = pd.DataFrame([item for sublist in participants_info_series for item in sublist])
    dk.drop('participants', axis=1, inplace=True)
    
    # Обработка категорий участников
    print("Extracting participant categories...")
    extracted_categories = dk['participant_categories'].apply(extract_participant_categories)
    dk = pd.concat([dk, extracted_categories], axis=1)
    dk.drop('participant_categories', axis=1, inplace=True)

    print("End of copy function")
    
    return dk, drivers_info_df, participants_info_df


In [133]:
dk_processed, drivers_info_df_processed, participants_info_df_processed = copy(da)


Start of copy function
Converting data types...
Converting data types.tags..
Transforming 'point' column...
Transforming 'nearby' column...
Processing 'weather' column...
Processing 'datetime' column...
Extracting driver information...
Extracting road conditions...
Extracting participant information...
Extracting participant categories...
End of copy function


In [136]:
dk_processed.drop('geometry', axis=1, inplace=True)


In [143]:
dk_processed.to_csv('/Users/juliagrebeneva/Desktop/dk_processed.csv', index=False)
drivers_info_df_processed.to_csv('/Users/juliagrebeneva/Desktop/drivers_info_df_processed.csv', index=False)
participants_info_df_processed.to_csv('/Users/juliagrebeneva/Desktop/participants_info_df_processed.csv', index=False)

In [137]:
dk_processed.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1411646 entries, 0 to 1411645
Data columns (total 21 columns):
 #   Column                     Non-Null Count    Dtype 
---  ------                     --------------    ----- 
 0   id                         1411646 non-null  int32 
 1   tags                       1411646 non-null  object
 2   light                      1411646 non-null  object
 3   point                      1411646 non-null  object
 4   nearby                     1411646 non-null  object
 5   region                     1411646 non-null  object
 6   weather                    1411646 non-null  object
 7   category                   1411646 non-null  object
 8   severity                   1411646 non-null  object
 9   dead_count                 1411646 non-null  int16 
 10  injured_count              1411646 non-null  int16 
 11  parent_region              1411646 non-null  object
 12  participants_count         1411646 non-null  int16 
 13  date               

In [138]:
dk_processed.head()

id tags                                     light  \
0  2921076    1                       Светлое время суток   
1  2442272    1  В темное время суток, освещение включено   
2  2434809    1                       Светлое время суток   
3  2434807    1                       Светлое время суток   
4  2434806    1                       Светлое время суток   

                    point  \
0  [47.273191, 39.728757]   
1      [47.2867, 39.7442]   
2      [47.2544, 39.7711]   
3      [47.2267, 39.6728]   
4      [47.2608, 39.7683]   

                                                   nearby          region  \
0      Пешеходная инфраструктура, Развлекательные объекты  Ростов-на-Дону   
1                                         Жилая застройка  Ростов-на-Дону   
2                              Образовательные учреждения  Ростов-на-Дону   
3                                                          Ростов-на-Дону   
4  Пешеходная инфраструктура, Транспортная инфраструктура  Ростов-на-Дону   

    weather             category     severity  dead_count  injured_count  \
0      Ясно         Столкновение  С погибшими           1              1   
1  Пасмурно  Наезд на стоящее ТС       Легкий           0              1   
2      Ясно    Наезд на пешехода       Легкий           0              1   
3      Ясно         Столкновение       Легкий           0              1   
4      Ясно    Наезд на пешехода       Легкий           0              1   

        parent_region  participants_count        date      time road_surface  \
0  Ростовская область                   3  2023-11-05  09:05:00        Сухое   
1  Ростовская область                   3  2018-05-25  20:35:00        Сухое   
2  Ростовская область                   2  2016-09-06  14:00:00        Сухое   
3  Ростовская область                   2  2016-09-06  07:20:00        Сухое   
4  Ростовская область                   2  2016-09-06  06:40:00        Сухое   

                                                road_lack_safety_features  \
0                                                                  Другое   
1  Отсутствие, плохая различимость горизонтальной разметки проезжей части   
2                                                                  Другое   
3                                                                  Другое   
4                   Отсутствие пешеходных ограждений в необходимых местах   

   all_participants  pedestrians  motorcyclists  children  
0                 1            0              0         0  
1                 1            0              1         0  
2                 1            1              0         0  
3                 1            0              1         0  
4                 1            1              0         0

In [139]:
drivers_info_df_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2177204 entries, 0 to 2177203
Data columns (total 9 columns):
 #   Column                              Dtype  
---  ------                              -----  
 0   id                                  int64  
 1   year                                float64
 2   brand                               object 
 3   color                               object 
 4   model                               object 
 5   category                            object 
 6   driver_gender                       object 
 7   driver_violations                   object 
 8   driver_years_of_driving_experience  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 149.5+ MB


In [141]:
drivers_info_df_processed.head()

id    year                    brand  color                    model  \
0  2921076  2019.0                      ГАЗ  Белый        Прочие модели ГАЗ   
1  2921076  2014.0                      ВАЗ  Белый          Largus (Ларгус)   
2  2442272  1982.0                    VOLVO  Белый      Прочие модели Volvo   
3  2442272  2005.0  Прочие марки мотоциклов  Белый  Прочие марки мотоциклов   
4  2442272  2017.0                  RENAULT  Белый                    Logan   

                                                     category driver_gender  \
0                                          Прочая спецтехника       Мужской   
1                                  Прочие легковые автомобили       Мужской   
2                                          Прочие одноярусные       Мужской   
3  Мопеды с двигателем внутреннего сгорания менее 50 см. куб.       Мужской   
4                                    В-класс (малый) до 3,9 м       Мужской   

                                               driver_violations  \
0  [Неправильный выбор дистанции, Несоблюдение требований ОСАГО]   
1                                                             []   
2                                                             []   
3                                 [Неправильный выбор дистанции]   
4                                                             []   

   driver_years_of_driving_experience  
0                                 3.0  
1                                48.0  
2                                16.0  
3                                 6.0  
4                                 4.0

In [140]:
participants_info_df_processed.head()

id     role   gender  \
0  2434809  Пешеход  Женский   
1  2434806  Пешеход  Мужской   
2  2434823  Пешеход  Женский   
3  2434835  Пешеход  Женский   
4  2920956  Пешеход  Мужской   

                                                                                                                                                               violations  \
0                                                                                                                                                                      []   
1  [Переход через проезжую часть вне пешеходного перехода в зоне его видимости либо при наличии в непосредственной близости подземного (надземного) пешеходного перехода]   
2                                                                                                                     [Нахождение на проезжей части без цели её перехода]   
3                                                                                                                                   [Неподчинение сигналам регулирования]   
4  [Переход через проезжую часть вне пешеходного перехода в зоне его видимости либо при наличии в непосредственной близости подземного (надземного) пешеходного перехода]   

                                                                                                                                                                                                health_status  
0  Раненый, находящийся (находившийся)  на амбулаторном лечении, либо которому по характеру полученных травм обозначена необходимость амбулаторного лечения (вне зависимости от его фактического прохождения)  
1  Раненый, находящийся (находившийся)  на амбулаторном лечении, либо которому по характеру полученных травм обозначена необходимость амбулаторного лечения (вне зависимости от его фактического прохождения)  
2  Раненый, находящийся (находившийся)  на амбулаторном лечении, либо которому по характеру полученных травм обозначена необходимость амбулаторного лечения (вне зависимости от его фактического прохождения)  
3  Раненый, находящийся (находившийся)  на амбулаторном лечении, либо которому по характеру полученных травм обозначена необходимость амбулаторного лечения (вне зависимости от его фактического прохождения)  
4                                                                                                            Раненый, находящийся (находившийся) на амбулаторном лечении, либо в условиях дневного стационара

In [142]:
participants_info_df_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440949 entries, 0 to 440948
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype 
---  ------         --------------   ----- 
 0   id             440949 non-null  int64 
 1   role           440949 non-null  object
 2   gender         429739 non-null  object
 3   violations     440949 non-null  object
 4   health_status  440923 non-null  object
dtypes: int64(1), object(4)
memory usage: 16.8+ MB


## Гипотезы

В этой части мы будем рассматривать три предположения, а на основе их выдвенем 3 гипотезы и проверим их. Посмотрим какие предположения у нас есть и далее будем формулировать гипотезы для каждого.
- Водители со стажем 4-6 лет опаснее, чем новички с опытом до 3-х лет (рассматриваем только водителей, нарушивших пдд)
- В темное время суток отсутствие освещение делает ДТП опаснее.
- Большой транспорт опаснее (тип) (обе стороны, и виноватые и не виноватые)

Будем проводить статистические тесты. Для примера возьмем два теста t-test, z-критерий. Для их работы нужно выполнить следующие условия:

- должны быть сформулированы гипотезы.
- определены выборки по критериям.
- выборки должны быть представлены числовыми рядами.

### Водители со стажем 4-6 лет опаснее, чем новички с опытом до 3-х лет


Гипотеза для t-test: В ДТП с опытными водителями погибших не больше, чем с новичками. В ДТП с опытными водителями погибших больше, чем при ДТП с новичками.

Гипотезы для z-критерия: Доля ДТП опытных водителей с погибшими не превышает долю ДТП новичков, различия статитистически незначимы. Доля ДТП опытных водителей с погибшими выше доли ДТП новичков, различия статистически значимы.

Что нужно сделать: 
- Выделить водителей, нарушивших ПДД.
- Выделить из них новичков (1-3 лет опыта);
- Выделить опытных водителей (от 4-6 лет опыта);

In [1]:
import requests
from tqdm import tqdm
import os
import pandas as pd
import json 
import ast
from tqdm import tqdm
import matplotlib.pyplot as plt
from scipy import stats as st
from scipy.stats import spearmanr
import numpy as np
import math as mth

import warnings
warnings.filterwarnings('ignore')

/Users/juliagrebeneva/anaconda3/envs/da_practicum_env/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
# загрузим датафрейм с водителями
drivers_info_df_processed=pd.read_csv('/Users/juliagrebeneva/Desktop/drivers_info_df_processed.csv')

In [3]:
# оставим только, тех водителей, которые нарушили ПДД
drivers_with_violations = drivers_info_df_processed[drivers_info_df_processed['driver_violations'].apply(len) > 2]
# удалим водителей, у которых не указан опыт
drivers_with_violations = drivers_with_violations.dropna(subset=['driver_years_of_driving_experience'])
# оставляем водителей с опытом до 6 лет
drivers_with_violations = drivers_with_violations[drivers_with_violations['driver_years_of_driving_experience'] <= 6]
# проставляем каждому такому водителю категорию 0- новичок, 1- с опытом
drivers_with_violations['experience_category'] = drivers_with_violations['driver_years_of_driving_experience'].apply(lambda x: 0 if x <= 3 else 1).astype('int8')
# оставляем только id и статус
drivers_with_violations=drivers_with_violations[['id','experience_category']]
# и убираем дубликаты
drivers_with_violations=drivers_with_violations.drop_duplicates().reset_index(drop=True)

In [4]:
drivers_with_violations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 331645 entries, 0 to 331644
Data columns (total 2 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   331645 non-null  int64
 1   experience_category  331645 non-null  int8 
dtypes: int64(1), int8(1)
memory usage: 2.8 MB


In [5]:
drivers_with_violations['experience_category'].value_counts()

experience_category
0    169641
1    162004
Name: count, dtype: int64

Теперь из основного датасета присоединим погибших.

In [22]:
columns_of_interest = ['id', 'dead_count','light']
dk_processed = pd.read_csv('/Users/juliagrebeneva/Desktop/dk_processed.csv', usecols=columns_of_interest)


In [7]:
#объединяем датасеты
result = drivers_with_violations.merge(dk_processed, on = 'id', how = 'left')

In [8]:
result.head(3)

id  experience_category  dead_count
0  2921076                    0           1
1  2442272                    1           0
2  2434823                    1           0

In [9]:
result.groupby('experience_category')['dead_count'].agg(['count','max','mean','sum'])

count  max      mean    sum
experience_category                              
0                    169641   16  0.095873  16264
1                    162004   20  0.101460  16437

In [10]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 331645 entries, 0 to 331644
Data columns (total 3 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   331645 non-null  int64
 1   experience_category  331645 non-null  int8 
 2   dead_count           331645 non-null  int64
dtypes: int64(2), int8(1)
memory usage: 5.4 MB


По данным можно сказать, что разницы практически нет. В нашей выборке на 7 тысяч больше неопытных водителей, но при этом больше погибших в ДТП с опытными водителями.

In [11]:
# Посмотрим связь между числом погибших и статусом водителей.

result[['experience_category','dead_count']].corr(method= 'spearman')

experience_category  dead_count
experience_category             1.000000    0.008868
dead_count                      0.008868    1.000000

In [12]:
spearmanr(result[['experience_category','dead_count']])

SpearmanrResult(correlation=0.008867602451579332, pvalue=3.2763998724678267e-07)

Связь очень слабая.

Создаем 2 датасета с опытными и неопытными водителями.

In [13]:
dr_new = result[result['experience_category'] == 0]


In [14]:
dr_ex = result[result['experience_category'] == 1]


Теперь посмотрим соотношение между погибшими в ДТП у опытных и неопытных водителей внутри каждой группы

In [15]:
dead_new = len(dr_new[dr_new['dead_count'] != 0]['dead_count'])
alive_new = len(dr_new[dr_new['dead_count'] == 0]['dead_count'])
dead_ex = len(dr_ex[dr_ex['dead_count'] != 0]['dead_count'])
alive_ex = len(dr_ex[dr_ex['dead_count'] == 0]['dead_count'])

In [16]:
print(f'Новички\n\
    всего ДТП - {len(dr_new)}\n\
    ДТП с погибшими - {dead_new}\n\
    ДТП без погибших  - {alive_new}\n\
    Процент ДТП с погибшими {dead_new/len(dr_new):.2%}')

Новички
    всего ДТП - 169641
    ДТП с погибшими - 13065
    ДТП без погибших  - 156576
    Процент ДТП с погибшими 7.70%


In [17]:
print(f'Опытные\n\
    всего ДТП - {len(dr_ex)}\n\
    ДТП с погибшими - {dead_ex}\n\
    ДТП без погибших  - {alive_ex}\n\
    Процент ДТП с погибшими {dead_ex/len(dr_ex):.2%}')

Опытные
    всего ДТП - 162004
    ДТП с погибшими - 13256
    ДТП без погибших  - 148748
    Процент ДТП с погибшими 8.18%


Проводим тесты.

In [18]:
alpha = .05 # критический уровень статистической значимости

dead = np.array([dead_ex, dead_new])
all_part = np.array([len(dr_ex),len(dr_new)])


In [19]:
def z_test(successes, trials, alpha):


    alpha = alpha
    successes = successes
    trials = trials

    # пропорция успехов в первой группе:
    p1 = successes[0] / trials[0]

    # пропорция успехов во второй группе:
    p2 = successes[1] / trials[1]

    # пропорция успехов в комбинированном датасете:
    p_combined = (successes[0] + successes[1]) / (trials[0] + trials[1])

    # разница пропорций в датасетах
    difference = p1 - p2

    # считаем статистику в ст.отклонениях стандартного нормального распределения
    z_value = difference / mth.sqrt(p_combined * (1 - p_combined) *
                                    (1 / trials[0] + 1 / trials[1]))

    # задаем стандартное нормальное распределение (среднее 0, ст.отклонение 1)
    distr = st.norm(0, 1)

    p_value = (1 - distr.cdf(abs(z_value))) # гипотеза односторонняя поэтому без 2

    print('p-значение: ', p_value)

    if p_value < alpha:
        print('Отвергаем нулевую гипотезу: доля с погибшими в ДТП c опытными водителями больше, есть значимая разница')
    else:
        print(
            'Не получилось отвергнуть нулевую гипотезу, доля с погибшими в ДТП опытных водителей не больше'
        )



In [20]:
z_test(dead, all_part, alpha)

p-значение:  1.5116416451910197e-07
Отвергаем нулевую гипотезу: доля с погибшими в ДТП c опытными водителями больше, есть значимая разница


In [21]:
p_value = st.ttest_ind(dr_ex['dead_count'],
                       dr_new['dead_count'],
                       equal_var=False,
                       alternative='greater')[1]

print('p-значение: ', p_value)
if p_value > alpha:
    print('Не удалось отвергнуть нулевую гипотезу')
else:
    print('Нулевая гипотеза отвергнута')

p-значение:  1.4842744981664907e-05
Нулевая гипотеза отвергнута


Таким образом, можно сказать, что водители с опытом 4-6 опаснее в случае ДТП, но связь между погибшими и опытными водителями очень слабая.

### В темное время суток отсутствие освещение делает ДТП опаснее.



Расматриваем только темное время суток!

Гипотеза для t-test: В ДТП без освещение погибает не больше людей, чем с освещением. В ДТП без освещения погибших больше, чем с другими.

Гипотезы для z-критерия: Доля ДТП без освещения с погибшими не превышает долю ДТП остальных, различия статитистически незначимы. Доля ДТП без освещения с погибшими выше доли ДТП остальных, различия статистически значимы.

Что нужно сделать: 
- Выделить ДТП произошедшие в темное время суток;
- Выделить ДТП с освещением;
- Выделить ДТП без освещения;

In [23]:
# загрузим основной датасет и посмотрим какие есть варианты освещения
dk_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1411646 entries, 0 to 1411645
Data columns (total 3 columns):
 #   Column      Non-Null Count    Dtype 
---  ------      --------------    ----- 
 0   id          1411646 non-null  int64 
 1   light       1411646 non-null  object
 2   dead_count  1411646 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 32.3+ MB


In [24]:
dk_processed['light'].unique()

array(['Светлое время суток', 'В темное время суток, освещение включено',
       'Сумерки', 'В темное время суток, освещение отсутствует',
       'В темное время суток, освещение не включено', 'Не установлено'],
      dtype=object)

In [25]:
dk_processed_light=dk_processed

In [26]:
# удаляем строки которые не относятся к темному времени
dk_processed_light = dk_processed_light[(dk_processed_light['light'] != 'Светлое время суток') & (dk_processed_light['light'] != 'Сумерки')& (dk_processed['light'] != 'Не установлено')]
# ставим 0 - освещение включено, 1 - освещение отключено/отсутсвует
dk_processed_light['light_category'] = dk_processed_light['light'].apply(lambda x: 0 if x == 'В темное время суток, освещение включено' else 1).astype('int8')

In [27]:
dk_processed_light['light'].unique()

array(['В темное время суток, освещение включено',
       'В темное время суток, освещение отсутствует',
       'В темное время суток, освещение не включено'], dtype=object)

In [28]:
dk_processed_light.groupby('light_category')['dead_count'].agg(['count','max','mean','sum'])

count  max      mean    sum
light_category                              
0               313170   17  0.085790  26867
1               174884   17  0.281209  49179

In [29]:
dk_processed_light.info()

<class 'pandas.core.frame.DataFrame'>
Index: 488054 entries, 1 to 1411641
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype 
---  ------          --------------   ----- 
 0   id              488054 non-null  int64 
 1   light           488054 non-null  object
 2   dead_count      488054 non-null  int64 
 3   light_category  488054 non-null  int8  
dtypes: int64(2), int8(1), object(1)
memory usage: 15.4+ MB


Как мы видим на аварии без освещения приходится почти третья часть от всех ДТП, при этом число погибших в этих авариях почти в 2 раза больше, чем при освещении.

In [30]:
#посмотрим на зависимость между числом погибших и наличием/отсутствием освещения
dk_processed_light[['light_category','dead_count']].corr(method= 'spearman')

light_category  dead_count
light_category        1.000000    0.227565
dead_count            0.227565    1.000000

In [31]:
spearmanr(dk_processed_light[['light_category','dead_count']])

SpearmanrResult(correlation=0.22756467464719587, pvalue=0.0)

Есть слабая связь между этими двумя признаками. Создадим датасеты с ДТП со освещением и без.

In [32]:
dr_lighting = dk_processed_light[dk_processed_light['light_category'] == 0]


In [33]:
dr_durk = dk_processed_light[dk_processed_light['light_category'] == 1]


Теперь посмотрим соотношение между погибшими в ДТП с освещением и без внутри каждой группы.

In [34]:
dead_lighting = len(dr_lighting[dr_lighting['dead_count'] != 0]['dead_count'])
alive_lighting = len(dr_lighting[dr_lighting['dead_count'] == 0]['dead_count'])
dead_durk = len(dr_durk[dr_durk['dead_count'] != 0]['dead_count'])
alive_durk = len(dr_durk[dr_durk['dead_count'] == 0]['dead_count'])

In [35]:
print(f'С освещением\n\
    всего ДТП - {len(dr_lighting)}\n\
    ДТП с пострадавшими - {dead_lighting}\n\
    ДТП без пострадавших  - {alive_lighting}\n\
    Процент ДТП с пострадавшими {dead_lighting/len(dr_lighting):.2%}')

С освещением
    всего ДТП - 313170
    ДТП с пострадавшими - 24359
    ДТП без пострадавших  - 288811
    Процент ДТП с пострадавшими 7.78%


In [36]:
print(f'Без освещения\n\
    всего ДТП - {len(dr_durk)}\n\
    ДТП с погибшими - {dead_durk}\n\
    ДТП без погибших  - {alive_durk}\n\
    Процент ДТП с погибшими {dead_durk/len(dr_durk):.2%}')

Без освещения
    всего ДТП - 174884
    ДТП с погибшими - 41931
    ДТП без погибших  - 132953
    Процент ДТП с погибшими 23.98%


Проведем тесты.

In [37]:
dead = np.array([dead_durk, dead_lighting])
all_part = np.array([len(dr_durk),len(dr_lighting)])

In [38]:
def z_test(successes, trials, alpha):


    alpha = alpha
    successes = successes
    trials = trials

    # пропорция успехов в первой группе:
    p1 = successes[0] / trials[0]

    # пропорция успехов во второй группе:
    p2 = successes[1] / trials[1]

    # пропорция успехов в комбинированном датасете:
    p_combined = (successes[0] + successes[1]) / (trials[0] + trials[1])

    # разница пропорций в датасетах
    difference = p1 - p2

    # считаем статистику в ст.отклонениях стандартного нормального распределения
    z_value = difference / mth.sqrt(p_combined * (1 - p_combined) *
                                    (1 / trials[0] + 1 / trials[1]))

    # задаем стандартное нормальное распределение (среднее 0, ст.отклонение 1)
    distr = st.norm(0, 1)

    p_value = (1 - distr.cdf(abs(z_value))) # гипотеза односторонняя поэтому без 2

    print('p-значение: ', p_value)

    if p_value < alpha:
        print('Отвергаем нулевую гипотезу: доля с погибшими в ДТП без освещения больше, есть значимая разница')
    else:
        print(
            'Не получилось отвергнуть нулевую гипотезу, доля с погибшими в ДТП без освещения не больше'
        )



In [39]:
z_test(dead, all_part, alpha)

p-значение:  0.0
Отвергаем нулевую гипотезу: доля с погибшими в ДТП без освещения больше, есть значимая разница


In [40]:
p_value = st.ttest_ind(dr_durk['dead_count'],
                       dr_lighting['dead_count'],
                       equal_var=False,
                       alternative='greater')[1]

print('p-значение: ', p_value)
if p_value > alpha:
    print('Не удалось отвергнуть нулевую гипотезу')
else:
    print('Нулевая гипотеза отвергнута')

p-значение:  0.0
Нулевая гипотеза отвергнута


Можем удтверждать, что ДТП без освещения опаснее. Связь не высокая, поэтому могут быть и другие факторы.

### Большой транпорт опаснее (тип)


Гипотеза для t-test: В ДТП с большим траспортом погибает не больше людей, чем с легковым. В ДТП с большим транспортом погибших больше, чем с легковым.

Гипотезы для z-критерия: Доля ДТП с большим транспортом с погибшими не превышает долю ДТП остальных, различия статитистически незначимы. Доля ДТП с большим транспортом с погибшими выше доли ДТП остальных, различия статистически значимы.

Что нужно сделать: 
- Выделить все автомобили, участвующие в ДТП;
- Выделить ДТП с легковыми автомобилями;
- Выделить ДТП с большим транспортом;

In [42]:
# смотрим на наш датасет с автомобилями
drivers_info_df_processed.head(5)

id    year                    brand  color                    model  \
0  2921076  2019.0                      ГАЗ  Белый        Прочие модели ГАЗ   
1  2921076  2014.0                      ВАЗ  Белый          Largus (Ларгус)   
2  2442272  1982.0                    VOLVO  Белый      Прочие модели Volvo   
3  2442272  2005.0  Прочие марки мотоциклов  Белый  Прочие марки мотоциклов   
4  2442272  2017.0                  RENAULT  Белый                    Logan   

                                            category driver_gender  \
0                                 Прочая спецтехника       Мужской   
1                         Прочие легковые автомобили       Мужской   
2                                 Прочие одноярусные       Мужской   
3  Мопеды с двигателем внутреннего сгорания менее...       Мужской   
4                           В-класс (малый) до 3,9 м       Мужской   

                                   driver_violations  \
0  ['Неправильный выбор дистанции', 'Несоблюдение...   
1                                                 []   
2                                                 []   
3                   ['Неправильный выбор дистанции']   
4                                                 []   

   driver_years_of_driving_experience  
0                                 3.0  
1                                48.0  
2                                16.0  
3                                 6.0  
4                                 4.0

In [43]:
# выделяем из датасета только id и category для дальнейшей категоризации
drivers=drivers_info_df_processed[['id','category']]

In [44]:
drivers['category'].unique()

array(['Прочая спецтехника', 'Прочие легковые автомобили',
       'Прочие одноярусные',
       'Мопеды с двигателем внутреннего сгорания менее 50 см. куб.',
       'В-класс (малый) до 3,9 м',
       'С-класс (малый средний, компактный) до 4,3 м',
       'D-класс (средний) до 4,6 м', 'Фургоны', 'Троллейбусы',
       'Одноэтажные длиной от 5 до 8 м',
       'Минивэны и универсалы повышенной вместимости',
       'Бортовые грузовые автомобили', 'Одноэтажные длиной не более 5 м',
       'Мопеды с электродвигателем менее 4 кВт',
       'Е-класс (высший средний, бизнес-класс) до 4,9 м', 'Самосвалы',
       'А-класс (особо малый) до 3,5 м',
       'Одноэтажные длиной от 8 до 12 м', 'Седельные тягачи', 'Мотоциклы',
       'Иные ТС', 'Прочие грузовые автомобили', 'Велосипеды',
       'Транспортные средства оперативно-служебные для перевозки лиц, находящихся под стражей',
       'Легковые автомобили (без типа)', 'Бортовые',
       'Автобусы (без типа)', 'Цистерны',
       'Автомобили скорой медиц

Сделаем следующую категоризацию:

Легковые автомобили: 'С-класс (малый средний, компактный) до 4,3 м', 'D-класс (средний) до 4,6 м', 'Е-класс (высший средний, бизнес-класс) до 4,9 м', 'Легковые автомобили (без типа)', 'Спортивные (гоночные)'

Грузовые автомобили: 'Фургоны', 'Бортовые грузовые автомобили', 'Седельные тягачи', 'Самосвалы', 'Прочие грузовые автомобили', 'Грузовые автомобили (без типа)'

Автобусы и трамваи: 'Автобусы (без типа)', 'Троллейбусы', 'Трамваи', 'Школьные автобусы'

Специализированная техника: 'Прочая спецтехника', 'Медицинские комплексы на шасси транспортных средств', 'Транспортные средства для обслуживания нефтяных и газовых скважин', 'Специализированная техника военного назначения', 'Специализированная техника МВД', 'Специализированная снегоуборочная техника'

Мототранспорт: 'Мопеды с двигателем внутреннего сгорания менее 50 см. куб.', 'Мопеды с двигателем внутреннего сгорания более 50 см. куб.', 'Мотоциклы', 'Мотороллеры', 'Иные мототранспортные средства', 'Мотонарты, аэросани', 'Мотовелосипеды', 'Трициклы', 'Квадроциклы', 'Квадрициклы', 'Мотонарты, аэросани'

Прочие: Все остальные категории, которые не вошли в вышеуказанные группы.

Для нашей гипотезы будем сравнивать легковые автомобили - 1, Грузовые автомобили и Специализированная техника - 0, остальной транспорт не рассматриваем.

In [45]:
def map_vehicle_category(category):
    passenger_cars = ['С-класс (малый средний, компактный) до 4,3 м', 'D-класс (средний) до 4,6 м', 'Е-класс (высший средний, бизнес-класс) до 4,9 м', 'Легковые автомобили (без типа)', 'Спортивные (гоночные)']
    commercial_vehicles = ['Фургоны', 'Бортовые грузовые автомобили', 'Седельные тягачи', 'Самосвалы', 'Прочие грузовые автомобили', 'Грузовые автомобили (без типа)','Прочая спецтехника', 'Медицинские комплексы на шасси транспортных средств', 'Транспортные средства для обслуживания нефтяных и газовых скважин', 'Специализированная техника военного назначения', 'Специализированная техника МВД', 'Специализированная снегоуборочная техника']
    
    if category in passenger_cars:
        return 1
    elif category in commercial_vehicles:
        return 0
    else:
        return 'NON'

# Применяем функцию к столбцу 'category' и создаем новый столбец 'vehicle_category'
drivers['vehicle_category'] = drivers['category'].apply(map_vehicle_category)


In [46]:
drivers = drivers[(drivers['vehicle_category'] != 'NON')]


In [47]:
drivers.head()

id                                      category vehicle_category
0  2921076                            Прочая спецтехника                0
5  2434809  С-класс (малый средний, компактный) до 4,3 м                1
7  2434807                    D-класс (средний) до 4,6 м                1
8  2434806                    D-класс (средний) до 4,6 м                1
9  2434823  С-класс (малый средний, компактный) до 4,3 м                1

In [49]:
drivers=drivers.drop_duplicates().reset_index(drop=True)

In [50]:
drivers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 671547 entries, 0 to 671546
Data columns (total 3 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   id                671547 non-null  int64 
 1   category          671547 non-null  object
 2   vehicle_category  671547 non-null  object
dtypes: int64(1), object(2)
memory usage: 15.4+ MB


In [51]:
# к получившимуся датасету цепляем основной
result = drivers.merge(dk_processed, on = 'id', how = 'left')

In [52]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 671547 entries, 0 to 671546
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   id                671547 non-null  int64 
 1   category          671547 non-null  object
 2   vehicle_category  671547 non-null  object
 3   light             671547 non-null  object
 4   dead_count        671547 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 25.6+ MB


In [53]:
result.groupby('vehicle_category')['dead_count'].agg(['count','max','mean','sum'])

count  max      mean    sum
vehicle_category                              
0                 180605   17  0.235453  42524
1                 490942   16  0.103318  50723

In [54]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 671547 entries, 0 to 671546
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   id                671547 non-null  int64 
 1   category          671547 non-null  object
 2   vehicle_category  671547 non-null  object
 3   light             671547 non-null  object
 4   dead_count        671547 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 25.6+ MB


Получается, что ДТП с большим траспортном составляют 4-ую часть от всех дтп, но в них погибает почти столько же человек, сколько в ДТП с лешковыми автомобилями.

In [55]:
result[['vehicle_category','dead_count']].corr(method= 'spearman')

vehicle_category  dead_count
vehicle_category          1.000000   -0.143545
dead_count               -0.143545    1.000000

In [56]:
spearmanr(result[['vehicle_category','dead_count']])

SpearmanrResult(correlation=-0.14354534167184507, pvalue=0.0)

Мы видим слабую отрицательную связь. Возможно сушествуют еще другие признаки.

Создадим датасеты с большим и легковым трнспортом.

In [58]:
dr_big = result[result['vehicle_category'] == 0]

In [59]:
dr_small = result[result['vehicle_category'] == 1]

Теперь посмотрим соотношение между погибшими в ДТП c разными видами транспорта внутри каждой группы.

In [60]:
dead_big = len(dr_big[dr_big['dead_count'] != 0]['dead_count'])
alive_big = len(dr_big[dr_big['dead_count'] == 0]['dead_count'])
dead_small = len(dr_small[dr_small['dead_count'] != 0]['dead_count'])
alive_small = len(dr_small[dr_small['dead_count'] == 0]['dead_count'])

Посмотрим долю ДТП с погибшими.

In [63]:
print(f'Большие\n\
    всего ДТП - {len(dr_big)}\n\
    ДТП с погибшими - {dead_big}\n\
    ДТП без погибших  - {alive_big}\n\
    Процент ДТП с погибшими {dead_big/len(dr_big):.2%}')

Большие
    всего ДТП - 180605
    ДТП с погибшими - 33706
    ДТП без погибших  - 146899
    Процент ДТП с погибшими 18.66%


In [64]:
print(f'Легковые\n\
    всего ДТП - {len(dr_small)}\n\
    ДТП с погибшими - {dead_small}\n\
    ДТП без погибших  - {alive_small}\n\
    Процент ДТП с погибшими {dead_small/len(dr_small):.2%}')

Легковые
    всего ДТП - 490942
    ДТП с погибшими - 41616
    ДТП без погибших  - 449326
    Процент ДТП с погибшими 8.48%


In [65]:
alpha = .05 # критический уровень статистической значимости

dead = np.array([dead_big, dead_small])
all_part = np.array([len(dr_big),len(dr_small)])


In [66]:
def z_test(successes, trials, alpha):


    alpha = alpha
    successes = successes
    trials = trials

    # пропорция успехов в первой группе:
    p1 = successes[0] / trials[0]

    # пропорция успехов во второй группе:
    p2 = successes[1] / trials[1]

    # пропорция успехов в комбинированном датасете:
    p_combined = (successes[0] + successes[1]) / (trials[0] + trials[1])

    # разница пропорций в датасетах
    difference = p1 - p2

    # считаем статистику в ст.отклонениях стандартного нормального распределения
    z_value = difference / mth.sqrt(p_combined * (1 - p_combined) *
                                    (1 / trials[0] + 1 / trials[1]))

    # задаем стандартное нормальное распределение (среднее 0, ст.отклонение 1)
    distr = st.norm(0, 1)

    p_value = (1 - distr.cdf(abs(z_value))) # гипотеза односторонняя поэтому без 2

    print('p-значение: ', p_value)

    if p_value < alpha:
        print('Отвергаем нулевую гипотезу: доля с погибшими в ДТП на больших машинах больше, есть значимая разница')
    else:
        print(
            'Не получилось отвергнуть нулевую гипотезу, доля с погибшими в ДТП на больших машинах не больше'
        )


In [67]:
z_test(dead, all_part, alpha)

p-значение:  0.0
Отвергаем нулевую гипотезу: доля с погибшими в ДТП на больших машинах больше, есть значимая разница


In [69]:
p_value = st.ttest_ind(dr_big['dead_count'],
                       dr_small['dead_count'],
                       equal_var=False,
                       alternative='greater')[1]

print('p-значение: ', p_value)
if p_value > alpha:
    print('Не удалось отвергнуть нулевую гипотезу')
else:
    print('Нулевая гипотеза отвергнута')

p-значение:  0.0
Нулевая гипотеза отвергнута


По результатам тестов, можно утверждать, что при ДТП с большим транспортом погибает больше людей, чем при ДТП с легковыми автомобилями.